# 设置时间源服务器【重要：集群内机器时间必须同步】
ntp_servers:
  - "ntp.aliyun.com"
  - "ntp.tencent.com"
  - "ntp.tuna.tsinghua.edu.cn"
  - "ntp.ntsc.ac.cn"

# 设置允许内部时间同步的网络段，比如"10.0.0.0/8"，默认全部允许
local_network: "0.0.0.0/0"

timeserver: "groups['chrony'][0]"