- name: 为普通用户增加环境变量
  copy:
    dest: /etc/profile.d/custom.sh
    content: |
      # Ensure /usr/sbin and /usr/local/sbin are in PATH
      if [[ ":$PATH:" != *":/usr/sbin:"* ]]; then
          PATH="${PATH}:/usr/sbin"
      fi

      if [[ ":$PATH:" != *":/usr/local/sbin:"* ]]; then
          PATH="${PATH}:/usr/local/sbin"
      fi
- name: Download curl from specified URL
  get_url:
    url: "{{ curl_url }}"
    dest: /opt/curl-7.79.1-oe2203sp4.tar.gz
- name: Extract curl tarball
  unarchive:
    src: /opt/curl-7.79.1-oe2203sp4.tar.gz
    dest: /opt/
    remote_src: yes
- name: Backup existing curl binary
  command: mv /usr/bin/curl /usr/bin/curl.bak
  ignore_errors: yes
- name: Create symlink for new curl binary
  file:
    src: /opt/curl-7.79.1/bin/curl
    dest: /usr/bin/curl
    state: link
